@startuml

class Utente{
nome : string
cognome : string
telefono: string 
email : string
supervisore : bool
}


class Admin extends Utente{
}

class Cameriere extends Utente{
tavoliServiti: int
inviaOrdineAllaCucina(Ordinazione ordine)
}

class AddettoCucina extends Utente{
ordiniEvasi : int
evadiOrdine(Ordinazione ordine)
}


class Ristorante{
nome: string
indirizzo: string
telefono : string
sitoWeb : string
fotoPath : string

getters e setters
}



class Elemento{
nome: string
descrizione : string
prezzo: float
ingredienti [string]
allergeni [string]

getters e setters
}

class ElementoConQuantita extends Elemento{
quantita : int
}

class Categoria{
nome : string
}

Categoria "1" --> "N" Elemento : composta

abstract class Menu{

}

Menu "1" --> "N" Categoria : ha



class Tavolo{
occupato : bool
id: int

chiudiTavolo()
stampaConto()
}

Ordinazione "1" --> "N" ElementoConQuantita: ha

Tavolo "1" --> "N" Ordinazione : prende

Admin "1" --> "N" Ristorante : ha

Ristorante "1" --> "1" Menu: ha
Ristorante "1" --> "N" AddettoCucina: ha
Ristorante "1" --> "N" Cameriere: ha

class Ordinazione {
uuid: int
timestamp : Datetime
evaso : bool

evadiOrdine()
}


@enduml