version: '3.9'

services:
  node-frontend:
    container_name: node-client
    restart: on-failure
    build: client/.
    ports:
      - "80:3000"
    depends_on:
      - node-backend
  node-backend:
    container_name: node-server
    restart: on-failure
    build: backend/.
    ports:
      - "3000:3000"
    depends_on:
      - node-db
  node-db:
    container_name: node-db
    image: postgres
    ports:
      - "42069:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=ratatouille
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
  storybook:
    container_name: storybook
    restart: on-failure
    build:
      context: client/.
      dockerfile: Dockerfile-storybook # Specifica il nome del Dockerfile per Storybook
    ports:
      - "6006:6006"
    depends_on:
      - node-frontend
