@startuml
class CucinaRoute <<Boundary>>{
isUsingFirstAccessPassword : bool
isScreenTooSmall : bool
SetIsScreenTooSmall(val : bool)  : void
cambiaPassword(val : bool) : void
mostraOrdinazioniDaEvadere() : void
mostraOrdinazioniEvaseUltime24h() : void
}

class Controller <<Control>> #coral{
/* ... altri metodi */
getOrdinazioniDaEvadere() : Promise<Ordinazioni>
getOrdinazioniEvaseUltime24h() : Promise<Ordinazioni>


}

class ItemOrdinazioneCucina <<Boundary>> {

    ordine: Ordinazione
    evasa: boolean

}


class NavBar <<Boundary>> {

	addFunc: () : void
	backFunc: () : void
	state: string[]
}

class ResettaPasswordPopup <<Boundary>> {

    onConfirm: (password: string) : void
    handleClickOnConfirm: () : void

}
class LoadingCircle <<Boundary>> {

	loaderPosition: string

}

NavBar --* CucinaRoute : contiene
LoadingCircle --* CucinaRoute : contiene
ResettaPasswordPopup --* CucinaRoute : contiene
ItemOrdinazioneCucina "*"--* CucinaRoute : contiene


Controller --* CucinaRoute : usa
@enduml