@startuml


class Controller <<Control>> #coral{
/* ... altri metodi */
getRistorante(id : string) : Promise<Ristorante>
}

class DashboardRistoranteRoute <<Boundary>> {
id : number
mostraRistorante() : void
}


class NavBar <<Boundary>> {

	addFunc: () : void
	backFunc: () : void
	state: string[]
}

class WelcomePanel <<Boundary>> {

    title: string
    subtitle: string

}





WelcomePanel--* DashboardRistoranteRoute: contiene
NavBar --* DashboardRistoranteRoute: contiene


Controller --* DashboardRistoranteRoute: usa
@enduml