@startuml


class Controller <<Control>> #coral{
/* ... altri metodi */
getRistoranteAttuale() : Promise<Ristorante>
}

class DashboardSupervisoreRoute <<Boundary>> {
isUsingFirstAccessPassword : bool
cambiaPassword(val : bool) : void
mostraRistoranteAttuale() : void
}


class NavBar <<Boundary>> {

	addFunc: () : void
	backFunc: () : void
	state: string[]
}

class ResettaPasswordPopup <<Boundary>> {

    onConfirm: (password: string) : void
    handleClickOnConfirm: () : void

}


class WelcomePanel <<Boundary>> {

    title: string
    subtitle: string

}





WelcomePanel--* DashboardSupervisoreRoute : contiene
NavBar --* DashboardSupervisoreRoute : contiene

ResettaPasswordPopup --* DashboardSupervisoreRoute : contiene
Controller --* DashboardSupervisoreRoute : usa
@enduml