@startuml


class Controller <<Control>> #coral{
/* ... altri metodi */
creaRistorante(ristorante : Ristorante) : void
}

class DashboardRoute <<Boundary>> {
navigate : NavigateFunction
utenteCorrente : Utente
saveIdRistorante : number
showModal : bool
setModal(val : bool)
setSavedIdRistorante(val : number) : void
setUtenteCorrente(utente : Utente) : void
informazioniRistorante : dictionary
setInformazioniRistorante(info : dictionary) : void

salvaIdRistoranteEAvanza (id: number) : void
handleOnChangeInformazioniRistorante() : void
aggiungiRistorante() : void
resettaCampi() : void
}


class NavBar <<Boundary>> {

	addFunc: () : void
	backFunc: () : void
	state: string[]
}

class WelcomePanel <<Boundary>> {

    title: string
    subtitle: string

}


class ItemRistorante <<Boundary>> {

    ristorante: Ristorante
    onClick: () : void

}

class SlideUpModal <<Boundary>> {

	showModal: boolean
	setShowModal: (showModal: boolean) : void
	children: React.ReactNode
	onClose: () : void

}

SlideUpModal --* DashboardRoute: contiene
ItemRistorante "*"--* DashboardRoute: contiene
WelcomePanel--* DashboardRoute: contiene
NavBar --* DashboardRoute: contiene


Controller --* DashboardRoute : usa
@enduml