@startuml


class Controller <<Control>> #coral{
/* ... altri metodi */
chiudiConto(conto : Conto) : void
getContiTavoliUltime24h() : Promise<Conto[]>
}

class GestisciContiRoute<<Boundary>> {
navigate : NavigateFunction
idRistorante : number
setIdRistorante(val : number)  : void
contoSelezionato : Conto
setContoSelezionato(conto : Conto) : void
chiudiConto(conto : Conto) : void
chiudiEStampaConto()
mostraContiTavoliUltime24h()
}


class NavBar <<Boundary>> {

	addFunc: () : void
	backFunc: () : void
	state: string[]
}



class WelcomePanel <<Boundary>> {

    title: string
    subtitle: string

}




class ItemOrdineTavolo <<Boundary>> {

    conto: Conto
    onClick: () : void

}
class ELementoOrdinazioneSupervisore <<Boundary>> {

    ordine: Ordinazione

}
ELementoOrdinazioneSupervisore "*"--* GestisciContiRoute: contiene
ItemOrdineTavolo "*"--* GestisciContiRoute: contiene

WelcomePanel--* GestisciContiRoute: contiene
NavBar --* GestisciContiRoute: contiene

Controller --* GestisciContiRoute: usa
@enduml