@startuml


class Controller <<Control>> #coral{
/* ... altri metodi */
getCategorie() : Promise<Categoria[]>
creaCategoria(Categoria categoria) : void 
}

class GestisciCategorieRoute<<Boundary>> {
 id : number
 showModal : bool
setModal(val : bool) : void
nomeCategoria : string 
setNomeCategoria(nome : string)
aggiungiCategoria() : void
mostraCategorie() : void

}


class NavBar <<Boundary>> {

	addFunc: () : void
	backFunc: () : void
	state: string[]
}



class WelcomePanel <<Boundary>> {

    title: string
    subtitle: string

}



class SlideUpModal <<Boundary>> {

	showModal: boolean
	setShowModal: (showModal: boolean) : void
	children: React.ReactNode
	onClose: () : void

}

class ItemCategoria <<Boundary>> {

    categoria: Categoria

}
ItemCategoria "*"--* GestisciCategorieRoute: contiene
SlideUpModal --* GestisciCategorieRoute: contiene
WelcomePanel--* GestisciCategorieRoute: contiene
NavBar --* GestisciCategorieRoute: contiene

Controller --* GestisciCategorieRoute: usa
@enduml