@startuml login_route

class Controller <<Control>> #coral{
  
  registraUtente(email: string, password: string) : Promise<boolean>
  accediUtente(email: string, password: string) : Promise<LoginPayLoad>

}

class LoginRoute {
  loginInfo: LoginInfo
  setLoginInfo(info: LoginInfo): void

  controller: Controller

  isLoading: boolean
  isLogging: boolean

  setIsLoading(value: boolean): void
  setIsLoading(value: boolean): void


  handleInfoLogin(e: React.ChangeEvent): void
  handleLoginRegister(email:string, password: string, passwordVerifica: string): void

}

class InputBox <<Boundary>> {

	value: string
	placeholder: string
	name: string
	type: string
	onChange: (event: React.ChangeEvent<HTMLInputElement>) : void
	onKeyDown: (event: React.KeyboardEvent<HTMLInputElement>) : void

}

class BigButton <<Boundary>> {

  onClick: () : void
  text: string
  color: string
  disabled: boolean

}





BigButton --* LoginRoute : contiene
InputBox--* LoginRoute : contiene
Controller --* LoginRoute : usa

@enduml



