@startuml


class Controller <<Control>> #coral{
/* ... altri metodi */
getRistorante(id : string) : Promise<Ristorante>
}

class DashboardRistorante <<Boundary>> {
id : number
mostraRistorante() : void
}




Controller --* DashboardRistorante: usa
@enduml
