@startuml


class Controller <<Control>> #coral{
/* ... altri metodi */
getCategorie() : Promise<Categoria[]>
creaCategoria(Categoria categoria) : void 
modificaCategoria(c : Categoria, id : number) : void
}

class GestisciCategorie<<Boundary>> {
nomeNuovaCategoria : string 

aggiungiCategoria() : void
mostraCategorie() : void
modificaCategoria() : void

}



class ItemCategoria <<Boundary>> {

    categoria: Categoria

}
ItemCategoria "*"--* GestisciCategorie: contiene


Controller --* GestisciCategorie: usa
@enduml