@startuml Statistiche

class Controller <<Control>> #coral {
    /* ... altri metodi */
    getUtenti(id: number): Promise<Utente[]>
    getNumeroOrdiniEvasiPerUtente(): Promise<{giorno: string, numero_ordinazioni: number}[]>

}

class Statistiche <<Boundary>> {
  selectedEmailUser: string
  id: string
  startDate: string;
  endDate: string

  mostraUtentiCucina() : void
  mostraOrdiniEvasi() : void
  aggiornaTimeSpan() : void
  aggiornaRangeDate(): void

}


class Chart {
  setData(data) : void
  plot() : void
  /* libreria esterna */
}



Chart--* Statistiche : contiene


Controller--* Statistiche : usa
@enduml
