@startuml
class CucinaRoute <<Boundary>>{
ordinazioni : Ordinazione[]
mostraOrdinazioniDaEvadere() : void
mostraOrdinazioniEvaseUltime24h() : void
}

class Controller <<Control>> #coral{
/* ... altri metodi */
getOrdinazioniDaEvadere() : Promise<Ordinazioni>
getOrdinazioniEvaseUltime24h() : Promise<Ordinazioni>


}

class ItemOrdinazioneCucina <<Boundary>> {

    ordine: Ordinazione
    evasa: boolean

}


ItemOrdinazioneCucina "*"--* CucinaRoute : contiene


Controller --* CucinaRoute : usa
@enduml