@startuml


class Controller <<Control>> #coral{
/* ... altri metodi */
creaRistorante(ristorante : Ristorante) : void
getRistoranti() : Ristorante[]
}

class DashboardRoute <<Boundary>> {
ristoranti : Ristorante[]
utenteCorrente : Utente
saveIdRistorante : number
mostraRistoranti() : void
aggiungiRistorante() : void
}


class ItemRistorante <<Boundary>> {

    ristorante: Ristorante

}



ItemRistorante "*"--* DashboardRoute: contiene



Controller --* DashboardRoute : usa
@enduml