@startuml


class Controller <<Control>> #coral{
/* ... altri metodi */
getRistorante(id : string) : Promise<Ristorante>
}

class DashboardRistoranteRoute <<Boundary>> {
id : number
mostraRistorante() : void
}




Controller --* DashboardRistoranteRoute: usa
@enduml
