@startuml


class Controller <<Control>> #coral{
  /* ... altri metodi */
  getUtenti(idRistorante: number): Promise<Utente[]>
}

class GestisciUtenzaRoute {


  utente: Utente
  

  mostraUtentiNelRistorante(): void
  aggiungiModificaUtente(infoUtente: Utente): void


  impostaInformazioniUtente(infoUtente: Utente): void
}

class UtenzaItem <<Boundary>> {

	utente: Utente

}





UtenzaItem "*"--* GestisciUtenzaRoute : contiene
Controller --* GestisciUtenzaRoute : usa

@enduml
