@startuml login_route

class Controller <<Control>> #coral{
  
  registraUtente(email: string, password: string) : Promise<boolean>
  accediUtente(email: string, password: string) : Promise<LoginPayLoad>

}

class LoginRoute {
  loginInfo: LoginInfo


  handleInfoLogin(event): void
  handleLoginRegister(email:string, password: string, passwordVerifica: string): void

}







Controller --* LoginRoute : usa

@enduml



