CREATE TABLE "Utente" (
  "id_utente" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_ristorante" int UNIQUE NOT NULL,
  "nome" string,
  "cognome" string,
  "telefono" string,
  "email" string,
  "supervisore" bool
);

CREATE TABLE "UtenteRistorante" (
  "id_utente" int UNIQUE NOT NULL,
  "id_ristorante" int UNIQUE NOT NULL,
  "is_admin" bool
);

CREATE TABLE "Ristorante" (
  "id_ristorante" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" string,
  "indirizzo" string,
  "telefono" string,
  "sito_web" string,
  "foto_path" string
);

CREATE TABLE "Categoria" (
  "id_categoria" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_ristorante" int UNIQUE NOT NULL,
  "nome" string
);

CREATE TABLE "Elemento" (
  "id_elemento" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_categoria" int UNIQUE NOT NULL,
  "nome" string,
  "descrizione" string,
  "prezzo" double,
  "ingredienti" string[],
  "allergeni" string[]
);

CREATE TABLE "Conto" (
  "id_conto" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "data" date
);

CREATE TABLE "Ordinazione" (
  "id_ordinazione" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_ristorante" int UNIQUE NOT NULL,
  "id_conto" int UNIQUE NOT NULL,
  "timestamp" datetime,
  "evaso" bool
);

CREATE TABLE "ElementoConQuantita" (
  "id_elemento" int UNIQUE NOT NULL,
  "id_ordinazione" int UNIQUE NOT NULL,
  "quantita" int
);

ALTER TABLE "UtenteRistorante" ADD FOREIGN KEY ("id_utente") REFERENCES "Utente" ("id_utente");

ALTER TABLE "UtenteRistorante" ADD FOREIGN KEY ("id_ristorante") REFERENCES "Ristorante" ("id_ristorante");

ALTER TABLE "Categoria" ADD FOREIGN KEY ("id_ristorante") REFERENCES "Ristorante" ("id_ristorante");

ALTER TABLE "Ordinazione" ADD FOREIGN KEY ("id_ristorante") REFERENCES "Ristorante" ("id_ristorante");

ALTER TABLE "Elemento" ADD FOREIGN KEY ("id_categoria") REFERENCES "Categoria" ("id_categoria");

ALTER TABLE "Ordinazione" ADD FOREIGN KEY ("id_conto") REFERENCES "Conto" ("id_conto");

ALTER TABLE "ElementoConQuantita" ADD FOREIGN KEY ("id_ordinazione") REFERENCES "Ordinazione" ("id_ordinazione");
